# Generated by Django 5.2.5 on 2025-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='drawing',
            field=models.FileField(upload_to='drawings/ '),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'New')], default='Новый', max_length=999999),
        ),
    ]
