# Generated by Django 5.2.5 on 2025-10-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_material_drawing_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='material',
            name='drawing',
            field=models.FileField(upload_to='drawings/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В работе', 'Inwork'), ('Выполнен', 'Done'), ('Не выполнен', 'Notdone')], default='Не выполнен', max_length=999999),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
